### ISSUE TITLE
IndexOutOfBoundsException

### ISSUE THREAD

**Issue by dondino77** [raymondchooi/react-native-circle-slider#9]
Hi @raymondchooi :
when I use the circle slider I often get this error. what can it depend on?
thx

2019-04-09 17:37:30.863 18373-18373/com.xxxx.mobile.rtl E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.xxxx.mobile.rtl, PID: 18373
    java.lang.IndexOutOfBoundsException: Index: 1, Size: 1
        at java.util.ArrayList.remove(ArrayList.java:503)
        at com.horcrux.svg.GlyphContext.popContext(GlyphContext.java:268)
        at com.horcrux.svg.GroupView.popGlyphContext(GroupView.java:74)
        at com.horcrux.svg.GroupView.drawGroup(GroupView.java:120)
        at com.horcrux.svg.GroupView.draw(GroupView.java:81)
        at com.horcrux.svg.RenderableView.render(RenderableView.java:309)
        at com.horcrux.svg.GroupView.drawGroup(GroupView.java:99)
        at com.horcrux.svg.GroupView.draw(GroupView.java:81)
        at com.horcrux.svg.UseView.draw(UseView.java:67)
        at com.horcrux.svg.RenderableView.render(RenderableView.java:309)
        at com.horcrux.svg.GroupView.drawGroup(GroupView.java:99)
        at com.horcrux.svg.GroupView.draw(GroupView.java:81)
        at com.horcrux.svg.RenderableView.render(RenderableView.java:309)
        at com.horcrux.svg.SvgView.drawChildren(SvgView.java:279)
        at com.horcrux.svg.SvgView.drawOutput(SvgView.java:232)
        at com.horcrux.svg.SvgView.onDraw(SvgView.java:89)

**Comment by raymondchooi** [comment]
I just tested it and it works fine for me, need more details as to what your code is, how you are using it, what device

**Comment by dondino77** [comment]
<CircleSlider
                    arcDirection={'CW'}
                    backgroundColor={'rgb(103,102,112)'}
                    btnRadius={20}
                    btnColor={'#4B62FF'}
                    sliderWidth={10}
                    startDegree={1}
                    maxValue={360}
                    showValue={true}
                    onValueChange={(value) => this.props.onChangeValue(value)}
                    value={this.state.value}
                    endGradient={"#4B62FF"}
                    startGradient={"#53E083"}
                />

device: nexus 5x with android 8.1.0

**Comment by raymondchooi** [comment]
I see you have some other props in there which means you have probably edited the CircleSlider component which is why it doesn't work and not an issue with the actual CircleSlider itself. Please try a basic CircleSlider (in the description) and see if that works first

**Comment by raymondchooi** [comment]
Closing this as it seems another circle slider was used, the npm package has now been updated to use the one found in this repository
